
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.3"

[[constraint]]
  name = "github.com/go-chi/cors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.1"

[[constraint]]
  name = "github.com/go-bongo/bongo"
  version = "0.10.4"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/go-chi/jwtauth"
  version = "4.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/sethvargo/go-password"
  version = "0.1.2"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  version = "2.0.0"

[[constraint]]
  name = "github.com/go-mail/mail"
  version = "2.3.1"
